/**
 * GENERATED by scripts/extract-pieces.js -- do not edit by hand.
 * Run: node scripts/extract-pieces.js assets/reference/Board.jpeg --board 30,305,532,531
 */
import type { ImageSourcePropType } from 'react-native';

export const PIECE_SPRITES: Partial<Record<string, ImageSourcePropType>> = {
  bk: require('../../../assets/pieces/bk.png'),
  bq: require('../../../assets/pieces/bq.png'),
  br: require('../../../assets/pieces/br.png'),
  bb: require('../../../assets/pieces/bb.png'),
  bn: require('../../../assets/pieces/bn.png'),
  bp: require('../../../assets/pieces/bp.png'),
  wk: require('../../../assets/pieces/wk.png'),
  wq: require('../../../assets/pieces/wq.png'),
  wr: require('../../../assets/pieces/wr.png'),
  wb: require('../../../assets/pieces/wb.png'),
  wn: require('../../../assets/pieces/wn.png'),
  wp: require('../../../assets/pieces/wp.png'),
};
