/**
 * Piece sprite catalog -- one require()'d SVG per (piece, color) per piece
 * set. Classic Chrome's 12 files ARE assets/pieces/*.svg directly (used
 * as-is, byte-for-byte); every locked variant lives in its own
 * assets/pieces/<variant-id>/ subdirectory. There is no runtime SVG
 * recoloring/generation -- every entry below is a plain require() so Metro
 * can statically resolve it (a dynamic template-literal require would not
 * bundle).
 *
 * Two different one-time authoring pipelines produce these files, per
 * variant (see src/constants/pieceSets.ts's per-entry comments for which is
 * which): scripts/vectorize-pieces.mjs traces bespoke hand-sourced renders
 * (genuinely different piece geometry), scripts/recolor-pieces.mjs
 * mixHex-blends the classic set's existing shapes toward an accent color
 * (transitional, only for variants without bespoke art yet).
 *
 * Hand-edited, not generated by a step that runs on every build -- mirrors
 * src/constants/boardThemes.ts's BOARD_THEMES ladder. Keep ids in sync with
 * src/constants/pieceSets.ts and server/src/pieceSets.ts.
 */
import type { ImageSourcePropType } from 'react-native';

export type PieceSpriteMap = Partial<Record<string, ImageSourcePropType>>;

const CLASSIC_CHROME: PieceSpriteMap = {
  bk: require('../../../assets/pieces/bk.svg'),
  bq: require('../../../assets/pieces/bq.svg'),
  br: require('../../../assets/pieces/br.svg'),
  bb: require('../../../assets/pieces/bb.svg'),
  bn: require('../../../assets/pieces/bn.svg'),
  bp: require('../../../assets/pieces/bp.svg'),
  wk: require('../../../assets/pieces/wk.svg'),
  wq: require('../../../assets/pieces/wq.svg'),
  wr: require('../../../assets/pieces/wr.svg'),
  wb: require('../../../assets/pieces/wb.svg'),
  wn: require('../../../assets/pieces/wn.svg'),
  wp: require('../../../assets/pieces/wp.svg'),
};

const GRAPHITE_TOUR: PieceSpriteMap = {
  bk: require('../../../assets/pieces/graphite-tour/bk.svg'),
  bq: require('../../../assets/pieces/graphite-tour/bq.svg'),
  br: require('../../../assets/pieces/graphite-tour/br.svg'),
  bb: require('../../../assets/pieces/graphite-tour/bb.svg'),
  bn: require('../../../assets/pieces/graphite-tour/bn.svg'),
  bp: require('../../../assets/pieces/graphite-tour/bp.svg'),
  wk: require('../../../assets/pieces/graphite-tour/wk.svg'),
  wq: require('../../../assets/pieces/graphite-tour/wq.svg'),
  wr: require('../../../assets/pieces/graphite-tour/wr.svg'),
  wb: require('../../../assets/pieces/graphite-tour/wb.svg'),
  wn: require('../../../assets/pieces/graphite-tour/wn.svg'),
  wp: require('../../../assets/pieces/graphite-tour/wp.svg'),
};

const MOLTEN_GOLD: PieceSpriteMap = {
  bk: require('../../../assets/pieces/molten-gold/bk.svg'),
  bq: require('../../../assets/pieces/molten-gold/bq.svg'),
  br: require('../../../assets/pieces/molten-gold/br.svg'),
  bb: require('../../../assets/pieces/molten-gold/bb.svg'),
  bn: require('../../../assets/pieces/molten-gold/bn.svg'),
  bp: require('../../../assets/pieces/molten-gold/bp.svg'),
  wk: require('../../../assets/pieces/molten-gold/wk.svg'),
  wq: require('../../../assets/pieces/molten-gold/wq.svg'),
  wr: require('../../../assets/pieces/molten-gold/wr.svg'),
  wb: require('../../../assets/pieces/molten-gold/wb.svg'),
  wn: require('../../../assets/pieces/molten-gold/wn.svg'),
  wp: require('../../../assets/pieces/molten-gold/wp.svg'),
};

const CRIMSON_REAPER: PieceSpriteMap = {
  bk: require('../../../assets/pieces/crimson-reaper/bk.svg'),
  bq: require('../../../assets/pieces/crimson-reaper/bq.svg'),
  br: require('../../../assets/pieces/crimson-reaper/br.svg'),
  bb: require('../../../assets/pieces/crimson-reaper/bb.svg'),
  bn: require('../../../assets/pieces/crimson-reaper/bn.svg'),
  bp: require('../../../assets/pieces/crimson-reaper/bp.svg'),
  wk: require('../../../assets/pieces/crimson-reaper/wk.svg'),
  wq: require('../../../assets/pieces/crimson-reaper/wq.svg'),
  wr: require('../../../assets/pieces/crimson-reaper/wr.svg'),
  wb: require('../../../assets/pieces/crimson-reaper/wb.svg'),
  wn: require('../../../assets/pieces/crimson-reaper/wn.svg'),
  wp: require('../../../assets/pieces/crimson-reaper/wp.svg'),
};

const PIECE_SPRITE_SETS: Record<string, PieceSpriteMap> = {
  'classic-pieces': CLASSIC_CHROME,
  'graphite-tour': GRAPHITE_TOUR,
  'molten-gold': MOLTEN_GOLD,
  'crimson-reaper': CRIMSON_REAPER,
};

export function getPieceSprites(id: string | null | undefined): PieceSpriteMap {
  return PIECE_SPRITE_SETS[id ?? ''] ?? CLASSIC_CHROME;
}
