/**
 * GENERATED by scripts/extract-pieces.js -- do not edit by hand.
 * Run: node scripts/extract-pieces.js assets/reference/Board.jpeg --board 30,305,532,531
 */
import type { ImageSourcePropType } from 'react-native';

export const PIECE_SPRITES: Partial<Record<string, ImageSourcePropType>> = {
  bk: require('../../../assets/pieces/bk.svg'),
  bq: require('../../../assets/pieces/bq.svg'),
  br: require('../../../assets/pieces/br.svg'),
  bb: require('../../../assets/pieces/bb.svg'),
  bn: require('../../../assets/pieces/bn.svg'),
  bp: require('../../../assets/pieces/bp.svg'),
  wk: require('../../../assets/pieces/wk.svg'),
  wq: require('../../../assets/pieces/wq.svg'),
  wr: require('../../../assets/pieces/wr.svg'),
  wb: require('../../../assets/pieces/wb.svg'),
  wn: require('../../../assets/pieces/wn.svg'),
  wp: require('../../../assets/pieces/wp.svg'),
};
